---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-0.4.0
  name: notification-service-ingress-notification-service-local
  namespace: notification-service
spec:
  hostnames:
    - notification-service.local
    - sous-chef-proxy.local
  parentRefs:
    - name: kong
      namespace: kong
  rules:
    - backendRefs:
        - name: notification-service
          port: 8000
      matches:
        - path:
            type: PathPrefix
            value: /api/v1/notification
status:
  parents: []
